### ISSUE TITLE
Retrieving Deleted Datasets

### ISSUE THREAD

**Issue by glombiewski** [ArunaStorage/aruna#142] opened 2023-12-19 16:32 UTC
### Describe the bug
When trying to retrieve a deleted dataset via the Rust API, there is an invalid permissions error:

`TonicStatus { source: Status { code: Unauthenticated, message: "Unauthorized : status: Unauthenticated, message: \"Invalid permissions\", details: [], metadata: MetadataMap { headers: {} }", metadata: MetadataMap { headers: {"date": "Tue, 19 Dec 2023 16:23:06 GMT", "content-type": "application/grpc", "content-length": "0", "strict-transport-security": "max-age=15724800; includeSubDomains"} }, source: None } }
`

This makes the GetDatasets functionality unusable. Unfortunately, I did not find another way to find out whether a dataset is deleted or not without a GetDataset or GetDatasets call.

### To Reproduce
1. Create a Dataset.
2. Delete it.
3. Try to retrieve it.

### Expected behavior
The dataset should return with the Deleted status.

**Comment by St4NNi** [comment] 2023-12-22 09:43
Hey, yes this is a known issue and a fix is in preparation. 

The problem is that "Deleted" references are currently not used for the permission hierarchy.

**Comment by das-Abroxas** [comment] 2024-01-04 14:12
We have extended the permission check to include relations to deleted resources. This means that it is now possible again to retrieve the metadata of deleted resources via the specific Get functionality (with the appropriate permissions).


It would be great if you could give us some feedback and close the issue if the problem is solved.

**Closed** 2024-04-10 13:38 UTC
Labels: bug
